# Generated by Django 4.1.3 on 2022-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='media/')),
                ('key', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('ingredient', models.TextField()),
            ],
        ),
    ]
